# Generated by Django 5.1.1 on 2024-11-21 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('feature_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseSpecification',
            fields=[
                ('specification_id', models.AutoField(primary_key=True, serialize=False)),
                ('use_case_name', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('summary_description', models.TextField()),
                ('pre_conditions', models.TextField()),
                ('post_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', models.CharField(max_length=100)),
                ('controller', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('basic_path', models.TextField(blank=True, null=True)),
                ('alternative_path', models.TextField(blank=True, null=True)),
                ('sequence_stuff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usecase.sequencestuff')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='usecase.sequencestuff')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='usecase.sequencestuff')),
            ],
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence_stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='usecase.sequencestuff')),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('use_case_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_start', models.CharField(max_length=255)),
                ('feature_end', models.CharField(max_length=255)),
                ('relation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_connections', to='usecase.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_actor_step', models.TextField(blank=True, null=True)),
                ('exception_system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_actor_step', models.TextField(blank=True, null=True)),
                ('basic_system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_actor_step', models.TextField(blank=True, null=True)),
                ('alternative_system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='usecase.usecasespecification')),
            ],
        ),
    ]
