# Generated by Django 5.1.1 on 2024-11-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0004_remove_usecase_aktor_remove_usecase_fitur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecasespecification',
            old_name='postconditions',
            new_name='post_conditions',
        ),
        migrations.RenameField(
            model_name='usecasespecification',
            old_name='preconditions',
            new_name='pre_conditions',
        ),
        migrations.RenameField(
            model_name='usecasespecification',
            old_name='specification_desc',
            new_name='summary_description',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='alternative_path',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='basic_path',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='exceptions_path',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='specification_name',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='use_case',
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='actor',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='use_case_name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usecasespecification',
            name='specification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AlternativePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_actor_step', models.TextField(blank=True, null=True)),
                ('alternative_system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_actor_step', models.TextField(blank=True, null=True)),
                ('basic_system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_actor_step', models.TextField(blank=True, null=True)),
                ('exception_system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='usecase.usecasespecification')),
            ],
        ),
    ]
