# Generated by Django 5.1.1 on 2024-11-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0005_featureconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureconnection',
            name='use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_connections', to='usecase.usecase'),
        ),
    ]
