# Generated by Django 5.1.1 on 2024-11-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0005_rename_postconditions_usecasespecification_post_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasespecification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecase.actorfeature'),
        ),
    ]
