# Generated by Django 5.1.1 on 2024-11-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0006_alter_featureconnection_use_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureConnection',
        ),
    ]
