# Generated by Django 5.1.1 on 2024-11-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0007_alter_usecasespecification_actor_featureconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconnection',
            name='relation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
