# Generated by Django 5.1.1 on 2024-11-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0008_featureconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconnection',
            name='relation_type',
            field=models.CharField(choices=[('include', 'Include'), ('extend', 'Extend'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
