@startuml
left to right direction
skinparam packageStyle rectangle

actor dosen
actor mahasiswa
rectangle usecase {
  (login)
  (register)
  (upload tugas)
  (login)
  (upload materi)
}

mahasiswa -- (login)
mahasiswa -- (register)
mahasiswa -- (upload tugas)
dosen -- (login)
dosen -- (upload materi)
(register) .> (login) : extend
(login) .> (upload tugas) : include
(login) .> (upload materi) : include
@enduml