@startuml
actor "mahasiswa" as mahasiswa
mahasiswa --> "melakukan presensi"
actor "mahasiswa" as mahasiswa
mahasiswa --> "mengumpulkan tugas"
actor "dosen" as dosen
dosen --> "memberikan tugas"
actor "TU" as TU
TU --> "validasi presensi"
@enduml